version: '2'

services:
  contentor-magento2-web:
    image: alexcheng/magento2:2.2.1
    ports:
      - "7000:80"
    links:
      - contentor-magento2-db
    volumes:
      - ../:/var/www/contentor
    env_file:
      - dev-env
    working_dir: /var/www/html/
  contentor-magento2-db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - dev-env
