<p>
<h2>Machine Translation</h2>
<?php
$machineTranslationOptions = $this->helper('Contentor\LocalizationApi\Helper\MachineTranslationConfig')->getConfig();
?>
<select name="machineTranslation">
    <?php
    foreach ($machineTranslationOptions as $option) {
        print '<option value="' . $option['value'] . '"';
        if ($option['value'] == 'none') {
            print ' SELECTED';
        }
        print '>' . $option['label'] . '</option>';
    }
    ?>
</select><br />
<strong>Note:</strong> Some machine-translated content requires <strong>attributions</strong> to the machine-translation provider to be displayed. Please refer to our agreement and <a href="https://developer.contentor.com/concepts/machine-translation/#attributions" target="_blank">documentation</a> for more information.
</p>
