<p>
<h2>Machine Translation</h2>
<?php
use Magento\Framework\View\Element\Template;

/** @var Template $block */
$machineTranslationViewModel = $block->getData('machineTranslationViewModel');
$isVersioningEnabled = $machineTranslationViewModel->isVersioningEnabled();
$machineTranslationOptions = $machineTranslationViewModel ? $machineTranslationViewModel->getConfig() : '';

$configUrl = $this->getUrl(
    'adminhtml/system_config/edit/section/contentor_options'
);

?>
<select name="machineTranslation" <?php if($isVersioningEnabled): ?>disabled<?php endif;?>>
    <?php
    foreach ($machineTranslationOptions as $option) {
        print '<option value="' . $option['value'] . '"';
        if ($option['value'] == 'none') {
            print ' SELECTED';
        }
        print '>' . $option['label'] . '</option>';
    }
    ?>
</select><br />
<?php if($isVersioningEnabled): ?>
    <br />
    Currently machine-translation orders are not possible when you have versioning enabled, 
    please disable versioning in the Contentor <a href="<?=$configUrl; ?>">configuration</a> to use machine-translation.
    <br />
<?php endif;?>
<br />
<strong>Note:</strong> Some machine-translated content requires <strong>attributions</strong> to the machine-translation provider to be displayed. Please refer to our agreement and <a href="https://developer.contentor.com/concepts/machine-translation/#attributions" target="_blank">documentation</a> for more information.
</p>
