<?php

$isCategory = $block->getIsCategory();

if ( $isCategory ) {
    $path = \Contentor\LocalizationApi\Service\ConfigurationService::XML_PATH_CATEGORY_CONTENT_CREATION_FIELDS;
} else {
    $path = \Contentor\LocalizationApi\Service\ConfigurationService::XML_PATH_CONTENT_CREATION_FIELDS;
}

$contentCreationAttributesConfig = $this->helper('Contentor\LocalizationApi\Helper\Data')
    ->getConfig($path);

$contentCreationAttributesConfig = json_decode($contentCreationAttributesConfig, true);
$id = time();
?>

<table class="admin__control-table" id="contentor_options_contentCreation_fieldDetails">
    <thead>
        <tr>
            <th>Attributes</th>
            <th>Amount Of Words</th>
        </tr>
    </thead>
    <tbody id="configAttributesContentCreation">
        <?php foreach ( $contentCreationAttributesConfig as $key => $config ): ?>
            <tr id="_<?= $key ?>">
                <td> <p><?= ucfirst($config['attribute']); ?></p> </td>
                <td>
                    <input type="text" id="<?= $key ?>_word_count"
                           name="attributesConfig[][<?= $config['attribute'] ?>]" value="<?= $config['word_count']; ?>" class="required-entry">
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


