<?php

$isCategory = $block->getIsCategory();

if ( $isCategory ) {
    $path = \Contentor\LocalizationApi\Service\ConfigurationService::XML_PATH_CATEGORY_CONTENT_CREATION_FIELDS;
} else {
    $path = \Contentor\LocalizationApi\Service\ConfigurationService::XML_PATH_CONTENT_CREATION_FIELDS;
}

$contentCreationAttributesConfig = $this->helper('Contentor\LocalizationApi\Helper\Data')
    ->getConfig($path);

$contentCreationAttributesConfig = json_decode($contentCreationAttributesConfig, true);
$id = time();
?>

<table class="admin__control-table" id="contentor_options_contentCreation_fieldDetails">
    <thead>
        <tr>
            <th><?= __('Attributes') ?></th>
            <th><?= __('Amount Of Words') ?></th>
            <th><?= __('Field Type') ?></th>
            <th><?= __('Context Value') ?></th>
        </tr>
    </thead>
    <tbody id="configAttributesContentCreation">
        <?php foreach ( $contentCreationAttributesConfig as $key => $config ): ?>
            <tr id="_<?= $key ?>">
                <td> <p><?= ucfirst($config['attribute']); ?></p> </td>
                <td>
                    <input <?= $config['field_type'] == 'context' ? "style='display:none'" : '' ?> type="text" id="<?= $config['attribute'] ?>_word_count"
                           name="attributesConfig[<?= $config['attribute'] ?>][word_count]" value="<?= $config['word_count']; ?>" class="required-entry">
                </td>
                <td>
                    <input readonly="readonly"  type="text" id="<?= $config['attribute'] ?>_field_type"
                          name="attributesConfig[<?= $config['attribute'] ?>][field_type]" class="required-entry"
                          value="<?= $config['field_type'] ?>"
                </td>
                <td>
                    <input <?= $config['field_type'] != 'context' ? "style='display:none'" :'' ?> type="textarea" id="<?= $config['attribute'] ?>_context_value"
                           name="attributesConfig[<?= $config['attribute'] ?>][context_value]" value="">

                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <p>
        <?= __('Context Value: Contextual information to help writers with localization and content creation. System will take Magento attribute value if the it\'s null.');?>
    </p>
</table>


