<?php 
// $product = $this->helper('Contentor\LocalizationApi\Helper\Data')->getConfig('contentor_options/token/apitoken');
// $myTestText = $this->helper('Contentor\LocalizationApi\Helper\ContentorAPI')->getTestText(12);

//print '<a href="' . $this->getUrl("contentor/administration/checktoken/") . '">klick</a>';
?>
<p>
	<form method="post" action="<?php print $this->getUrl("contentor/administration/postproduct/"); ?>" name="contentorproducts">
	<input type="hidden" name="returnurl" value ="<?php print $this->getProduct()->getProductUrl(); ?>">
	<input type="hidden" name="productid" value ="<?php print $this->getProduct()->getId(); ?>">

	<h2>Source store locale</h2>
	<select name="source">
		<option value="">Choose source language</option>
			<?php
			$configLocale = $this->helper('Contentor\LocalizationApi\Helper\Data')->getConfig('contentor_options/source/sourcelocale');
			$localeList = $this->getLocales();
			foreach($localeList as $lang) {
				print '<option value="' . $lang['value'] . '"';
				if($lang['value'] == $configLocale) {
					print ' SELECTED';
				}
				print '>' . $lang['label'] . '</option>';
			}
			?>
	</select>
</p>
<br><br><br>
<p>
	<h2>Target store view(s)</h2>
			<?php

			// Get stores if sent before
			
			// Else get default stores
			$defaultstores = explode(',',$this->helper('Contentor\LocalizationApi\Helper\Data')->getConfig('contentor_options/targets/targetviews'));
			$storesStructure = $this->getStoreViews();
			
			foreach($storesStructure as $website) {
				print "<b>";
				print $website['label'];
				print "</b><br>";
				foreach($website['children'] as $store) {
					print "&nbsp;&nbsp;&nbsp;<b><i>";
					print $store['label'];
					print "</i></b><br>";
					foreach($store['children'] as $storeview) {
						$id = $storeview['value'];
						$name = $storeview['label'];
						$locale = $this->getStoreLocale($id);
						//str_replace('_', '-', Mage::getStoreConfig('general/locale/code', $id));
						if(in_array($id, $defaultstores)) {
							$checked = 'checked';
						} else {
							$checked = '';
						}
						print '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label><input type="checkbox" name="targets[]" value="' . $id . ':' . $locale . '" id="store_' . $id . '" ' . $checked . '> ' . $name . ' (' . $locale .')</label><br>';
					}
				}
			}

			?>
</p>
<br><br><br>
<p>
 <input type="submit" value="Send for localization" name="submitme">
 </form>
</p>
<br><br><br>
<p>
	<h3>Request status</h3>
			<?php 
			// Get and print log for this product
			$messages = $this->getRequestStatus($this->getProduct()->getSku());
			$lastId = '';
			if(count($messages)) {
				// I have content
				print '<ul class="messages">';
				foreach($messages as $message) {
					if($message['contentor_id'] != $lastId) {

						// If not for the first time ever print the end of prev.
						if($lastId) {
							print '</ul>';
							print '</li>';
						}
						
						// New request, print header and button if needed
						if($message['state'] == 'canceled') {
							// Product canceled
							print '<li class="error-msg">';
							print '<h4>Canceled</h4>';
						} else if($message['state'] == 'confirmed') {
							print '<li class="notice-msg">';
							print '<h4 style="float:left">Confirmed</h4>';
							print '<div class="form-buttons"></div>';
							print '<div style="clear:both"></div>';
							
						} else if($message['state'] == 'completed' || $message['completed_time'] != null) {
							// Product completed
							print '<li class="success-msg">';
							print '<h4>Completed ' . $message['completed_time'] . '</h4>';
						} else {
							print '<li class="notice-msg">';
							print '<h4 style="float:left">Sent ' . $message['sent_time'] . '</h4>';
							print '<div class="form-buttons"></div>';
							print '<div style="clear:both"></div>';
							
						}
						
						print '<p>Target store: ' . $message['target_store'] . '<br>';
						if(!empty($message['type'])) {
							$type = $message['type'];
						} else {
							$type = 'standard';
						}
						print 'Request type: ' . $type . '</p>';

						// Print the status rows
						$lastId = $message['contentor_id'];
						print '<hr>';
						print '<p><h5>Log messages</h5>';
						print '<ul>';
					}
					
					// This happens every iteration
					print '<li><i>' . $message['status_time'] . '</i> - ' . $message['status'] . '</li>';
					
				}
				print '</ul></p>';
				print '</li>';
				print '</ul>';
			} else {
				print "<i>(No events to show)</i>";
			}
			?>

</p>

<script type="text/javascript">
//<![CDATA[
	function fetchSingle(id, type) {
		new Ajax.Request('', {
			method:     'GET',
			parameters: { id, type },
			onSuccess: function(transport) {
				if(transport.responseText) {
				// If response was that changes was found, reload page if user wants to!
					if(confirm('Changes was found, reload page?')) {
							location.reload();
					} else {
						return false;
					}
				} else {
					alert('No state changes was found');
				}
			}
		});
	}
//]]>
</script>