<?php

use Contentor\LocalizationApi\Block\System\Config\Widget\ProductImportActions;
use Magento\Framework\Escaper;

/**
 * @var ProductImportActions $block
 * @var Escaper $escaper
 */

?>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'mage/translate'
    ], function ($, mageAlert) {

        const startButton = $('#start_product_import_button');
        const retryButton = $('#retry_failed_imports_button');
        const clickAction = function(event) {
            const element = $(event.currentTarget);
            element.addClass('disabled');
            $.post(
                '<?= $escaper->escapeUrl($block->getSubmitUrl()) ?>',
                {
                    form_key: "<?= $escaper->escapeHtml($block->getFormKey()) ?>",
                    retry_failed: event.currentTarget.id === 'retry_failed_imports_button' ? 1 : 0
                },
                function (response) {
                    mageAlert({
                        content: response.message,
                    });
                }
            ).fail(function () {
                mageAlert({
                    content: $.mage.translate('Unexpected error occurred. Please try again later.'),
                });
            }).always(function () {
                element.removeClass('disabled');
            });
        };

        startButton.click(clickAction);
        retryButton.click(clickAction);
    });
</script>
<?= /* @noEscape */ $block->getStartImportButtonHtml() ?>
<p><?= $escaper->escapeHtml(__('Last import finished:') . ' ' . $block->getLastImport()) ?></p>
<?= /* @noEscape */ $block->getRetryFailedImportsButtonHtml() ?>