<?php

use Contentor\LocalizationApi\Block\Adminhtml\Reports\CategoryReportBlock;
use Contentor\LocalizationApi\Block\Adminhtml\Reports\ContentCreationCategoryReportBlock;

/** @var CategoryReportBlock|ContentCreationCategoryReportBlock $block */

if ($block->getParameter('page')) {
    $page = abs($block->getParameter('page'));
}
if ($block->getParameter('pagesize')) {
    $pagesize = abs($block->getParameter('pagesize'));
}
if (empty($page)) {
    $page = 1;
}
if (empty($pagesize)) {
    $pagesize = 30;
}
// Pagination $page and $pagesize
$tot = $block->getTotal();
if ($tot > 0) {
    $nPages = ceil($tot / $pagesize);
    if ($page > $nPages) {
        $page = $nPages;
    }
    print 'Total ' . $escaper->escapeHtml($tot) . ' rows<br>';
    print 'Page: ';
    for ($i = 1; $i <= $nPages; $i++) {
        if ($i == $page) {
            print '<b>' . $escaper->escapeHtml($i) . '</b> ';
        } else {
            print '<a href="' . $escaper->escapeUrl($block->getPage($i)) . '">' . $escaper->escapeHtml($i) . '</a> ';
        }
    }
    print ' | ';
    if ($page > 1) {
        print '<a href="' . $escaper->escapeUrl($block->getPage($page - 1)) . '">Previous</a> ';
    }
    if ($page < $nPages) {
        print ' <a href="' . $escaper->escapeUrl($block->getPage($page + 1)) . '">Next</a> ';
    }

    $offset = ($page - 1) * $pagesize;
    $categoryList = $block->getCategoryList($offset, $pagesize);
    $n = count($categoryList);

    // Get stores
    $stores = $block->getStores();
    foreach ($stores as $store) {
        $id = $store['store_id'];
        if ($id != 0) {
            $name = $store['name'];
            $locale = $block->getStoreLocale($id);
            $storeInfo[$id] = $name;
            $storeLocale[$id] = $locale;
        }
    }
    $numStores = count($storeInfo); ?>
    <br><br>
    <div class="grid">
        <div class="hor-scroll">
            <table cellspacing=0>
                <thead>
                <tr class="headings">
                    <th>Category Id</th>
                    <th>Name</th>
                    <th>Source</th>
                    <th colspan=<?= $escaper->escapeHtmlAttr($numStores); ?>>Status</th>
                    <th>Delivery Speed</th>
                    <th>Machine Translation</th>
                    <th>Attributions</th>
                </tr>
                <tr class="headings">
                    <th></th>
                    <th></th>
                    <th></th>
                    <?php
                    foreach ($storeInfo as $id => $store) {
                        print '<th>' . $escaper->escapeHtml($store) . ' (' . $escaper->escapeHtml($storeLocale[$id]) . ')</th>';
                    } ?>
                </tr>
                </thead>
                <tbody>
                <?php
                $i = 0;
                foreach ($categoryList as $category) {
                    $details = $block->getCategory($category['category_id']);
                    if (!$details) {
                        continue;
                    }
                    $categoryName = $details->getName();
                    $url = $block->getUrl('catalog/category/edit', ['id' => $details->getId()]);
                    if ($i % 2) {
                        $even = '#eee';
                    } else {
                        $even = '#fff';
                    }

                    $sent = [];
                    if ($category['sent']) {
                        $sentStores = explode(",", $category['sent']);
                        foreach ($sentStores as $sentStore) {
                            if (!empty($sentStore)) {
                                $sentinfo = explode(";", $sentStore);
                                $sent[$sentinfo[0]] = $sentinfo[1];
                            }
                        }
                    }

                    $completed = [];
                    if ($category['completed']) {
                        $completeStores = explode(",", $category['completed']);
                        foreach ($completeStores as $completeStore) {
                            if (!empty($completeStore)) {
                                $completeinfo = explode(";", $completeStore);
                                $completed[$completeinfo[0]] = $completeinfo[1];
                            }
                        }
                    }

                    $state = [];
                    if ($category['state']) {
                        $stateStores = explode(",", $category['state']);
                        foreach ($stateStores as $stateStore) {
                            if (!empty($stateStore)) {
                                $stateinfo = explode(";", $stateStore);
                                $state[$stateinfo[0]] = $stateinfo[1];
                            }
                        }
                    }

                    print '<tr title="' . $escaper->escapeHtmlAttr($url) . '" style="background-color:' . $escaper->escapeHtmlAttr($even) . '; border-bottom:1px solid #aaa;">';
                    print '<td class=" " style="padding: 5px; padding-right: 15px;"><a href="' . $escaper->escapeUrl($url) . '">' . $escaper->escapeHtml($category['category_id']) . '</a></td>';
                    print '<td class=" " style="padding: 5px; padding-right: 15px;">' . $escaper->escapeHtml($categoryName) . '</td>';
                    print '<td class=" " style="padding: 5px; padding-right: 15px;">' . $escaper->escapeHtml($category['source']) . '</td>';
                    // Loop stores and print status for them
                    foreach ($storeInfo as $id => $name) {
                        // Check state
                        if (isset($state[$id])) {
                            // I have a state and I will use it!
                            if ($state[$id] == 'completed') {
                                print '<td style="padding: 5px; padding-right: 15px; background:#eff5ea;">';
                                print 'Received: ' . $escaper->escapeHtml($completed[$id]);
                            } elseif ($state[$id] == 'confirmed') {
                                print '<td style="padding: 5px; padding-right: 15px; background:#fffbf0;">';
                                print 'Confirmed (' . $escaper->escapeHtml($sent[$id]) . ')';
                            } elseif ($state[$id] == 'pending') {
                                print '<td style="padding: 5px; padding-right: 15px; background:#fffbf0;">';
                                print 'Sent: ' . $escaper->escapeHtml($sent[$id]);
                            } elseif ($state[$id] == 'canceled') {
                                print '<td style="padding: 5px; padding-right: 15px; background:#faebe7;">';
                                print 'Canceled';
                            }
                        } else {
                            if (isset($completed[$id])) {
                                print '<td style="padding: 5px; padding-right: 15px; background:#eff5ea;">';
                                print 'Received: ' . $escaper->escapeHtml($completed[$id]);
                            } elseif (isset($sent[$id])) {
                                print '<td style="padding: 5px; padding-right: 15px; background:#fffbf0;">';
                                print 'Sent: ' . $escaper->escapeHtml($sent[$id]);
                            } else {
                                print '<td style="padding: 5px; padding-right: 15px;">';
                                print 'Not sent';
                            }
                        }
                        print '</td>';
                    }
                    print '<td class=" " style="padding: 5px; padding-right: 15px;">' . $escaper->escapeHtml($category['deliverySpeed'] !== null ? ucwords($category['deliverySpeed']) : 'Normal') . '</td>';
                    print '<td class=" " style="padding: 5px; padding-right: 15px;">' . $escaper->escapeHtml($category['machineTranslation'] !== null ? ucwords($category['machineTranslation']) : 'None') . '</td>';
                    print '<td class=" " style="padding: 5px; padding-right: 15px;">' . $escaper->escapeHtml($category['attribution'] !== null ? ucwords($category['attribution']) : 'None') . '</td>';
                    print '</tr>';

                    $i++;
                } ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php
}
?>
