<?php
    $page = abs($block->getParameter('page'));
    $pagesize = abs($block->getParameter('pagesize'));
if (empty($page)) {
    $page = 1;
}
if (empty($pagesize)) {
    $pagesize = 30;
}
    // Pagination $page and $pagesize
    $tot = $block->getTotal();
if ($tot > 0) {
    $nPages = ceil($tot/$pagesize);
    if ($page > $nPages) {
        $page = $nPages;
    }
    print 'Total ' . $tot . ' rows<br>';
    print 'Page: ';
    for ($i=1; $i<=$nPages; $i++) {
        if ($i == $page) {
            print '<b>' . $i . '</b> ';
        } else {
            print '<a href="' . $this->getPage($i) . '">' . $i . '</a> ';
        }
    }
    print ' | ';
    if ($page > 1) {
        print '<a href="' . $this->getPage($page - 1) . '">Previous</a> ';
    }
    if ($page < $nPages) {
        print ' <a href="' . $this->getPage($page + 1) . '">Next</a> ';
    }

    $offset = ($page-1)*$pagesize;
    $productList = $block->getProductList($offset, $pagesize);
    $n = count($productList);

    // Get stores
    $stores = $block->getStores();
    foreach ($stores as $store) {
        $id = $store['store_id'];
        if ($id != 0) {
            $name = $store['name'];
            $locale = $block->getStoreLocale($id);
            $storeInfo[$id] = $name;
            $storeLocale[$id] = $locale;
        }
    }
    $numStores = count($storeInfo);

    ?>
    <br><br>
    <div class="grid">
        <div class="hor-scroll">
            <table cellspacing=0 >
                <thead>
                    <tr class="headings"><th>SKU</th><th>Name</th><th>Source</th><th colspan=<?php print $numStores;?>>Status</th></tr>
                    <tr class="headings"><th></th><th></th><th></th>
                <?php
                foreach ($storeInfo as $id => $store) {
                    print '<th>' . $store . ' (' . $storeLocale[$id] . ')</th>';
                }
                ?>
                    </tr>
                </thead>
                <tbody>
    <?php
    $i = 0;
    foreach ($productList as $prod) {
        $details = $block->getProduct($prod['sku']);
        $prodName = $details->getName();
        $url = $this->getUrl('catalog/product/edit', ['id' => $details->getId()]);
        if ($i%2) {
            $even = '#eee';
        } else {
            $even = '#fff';
        }

        $sent = [];
        $sentStores = explode(",", $prod['sent']);
        foreach ($sentStores as $sentStore) {
            if (!empty($sentStore)) {
                $sentinfo = explode(";", $sentStore);
                $sent[$sentinfo[0]] = $sentinfo[1];
            }
        }

        $completed = [];
        $completeStores = explode(",", $prod['completed']);
        foreach ($completeStores as $completeStore) {
            if (!empty($completeStore)) {
                $completeinfo = explode(";", $completeStore);
                $completed[$completeinfo[0]] = $completeinfo[1];
            }
        }

        $state = [];
        $stateStores = explode(",", $prod['state']);
        foreach ($stateStores as $stateStore) {
            if (!empty($stateStore)) {
                $stateinfo = explode(";", $stateStore);
                $state[$stateinfo[0]] = $stateinfo[1];
            }
        }

        print '<tr title="' . $url . '" style="background-color:' . $even . '; border-bottom:1px solid #aaa;">';
        print '<td class=" " style="padding: 5px; padding-right: 15px;"><a href="' . $url . '">' . $prod['sku'] . '</a></td>';
        print '<td class=" " style="padding: 5px; padding-right: 15px;">' . $prodName . '</td>';
        print '<td class=" " style="padding: 5px; padding-right: 15px;">' . $prod['source'] . '</td>';
        // Loop stores and print status for them
        foreach ($storeInfo as $id => $name) {
            // Check state
            if (isset($state[$id])) {
                // I have a state and I will use it!
                if ($state[$id] == 'completed') {
                    print '<td style="padding: 5px; padding-right: 15px; background:#eff5ea;">';
                    print 'Received: ' . $completed[$id];
                } elseif ($state[$id] == 'confirmed') {
                    print '<td style="padding: 5px; padding-right: 15px; background:#fffbf0;">';
                    print 'Confirmed ('  . $sent[$id] . ')';
                } elseif ($state[$id] == 'pending') {
                    print '<td style="padding: 5px; padding-right: 15px; background:#fffbf0;">';
                    print 'Sent: ' . $sent[$id];
                } elseif ($state[$id] == 'canceled') {
                    print '<td style="padding: 5px; padding-right: 15px; background:#faebe7;">';
                    print 'Canceled';
                }
            } else {
                if (isset($completed[$id])) {
                    print '<td style="padding: 5px; padding-right: 15px; background:#eff5ea;">';
                    print 'Received: ' . $completed[$id];
                } elseif (isset($sent[$id])) {
                    print '<td style="padding: 5px; padding-right: 15px; background:#fffbf0;">';
                    print 'Sent: ' . $sent[$id];
                } else {
                    print '<td style="padding: 5px; padding-right: 15px;">';
                    print 'Not sent';
                }
            }
            print '</td>';
        }
        print '</tr>';

        $i++;
    }
    ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php
}
?>
