<p>
<h2>Machine Translation</h2>
<?php
use Magento\Framework\View\Element\Template;

/** @var Template $block */
$machineTranslationViewModel = $block->getData('machineTranslationViewModel');
$isVersioningEnabled = $machineTranslationViewModel->isVersioningEnabled();
$machineTranslationOptions = $machineTranslationViewModel ? $machineTranslationViewModel->getConfig() : '';

$configUrl = $this->getUrl(
    'adminhtml/system_config/edit/section/contentor_options'
);

?>
<select name="machineTranslation" <?php if($isVersioningEnabled): ?>disabled<?php endif;?> id="machine-translation-section">
    <?php
    foreach ($machineTranslationOptions as $option) {
        print '<option value="' . $option['value'] . '"';
        if ($option['value'] == 'none') {
            print ' SELECTED';
        }
        print '>' . $option['label'] . '</option>';
    }
    ?>
</select><br />


<div id="machine-translation-text" <?php if($isVersioningEnabled): ?> style="display: block;"<?php else:?> style="display: none;" <?php endif;?>>
    <br />
    Currently machine-translation orders are not possible when you have versioning enabled,
    please disable versioning in the Contentor <a href="<?=$configUrl; ?>">configuration</a> to use machine-translation.
    <br />
</div>

<br />
<strong>Note:</strong> Some machine-translated content requires <strong>attributions</strong> to the machine-translation provider to be displayed. Please refer to our agreement and <a href="https://developer.contentor.com/concepts/machine-translation/#attributions" target="_blank">documentation</a> for more information.
</p>

<script>
    require(['jquery'], function ($) {
        $(document).ready(function () {
            // Add an event listener to the Versioning select in versioning.phtml
            $('#versioning-select').on('change', function () {
                var selectedOption = $(this).val();
                var machineTranslationSection = $('#machine-translation-section');
                var machineTranslationText = $('#machine-translation-text');
                var isVersioningEnabledConfig = <?php echo json_encode($isVersioningEnabled); ?>;
                var isVersioningEnabled = (selectedOption == 'yes');

                // Check if Versioning is enabled in form and also configuration and show/hide the Machine Translation accordingly
                // Prioritize the form value over the configuration value

                if (isVersioningEnabled) {
                    machineTranslationText.show();
                    machineTranslationSection.prop('disabled', true);
                } else {
                    if(selectedOption == 'no') {
                        machineTranslationText.hide();
                        machineTranslationSection.prop('disabled', false);
                    }
                    if(selectedOption == 'default') {
                        if(isVersioningEnabledConfig) {
                            machineTranslationText.show();
                            machineTranslationSection.prop('disabled', true);
                        } else {
                            machineTranslationText.hide();
                            machineTranslationSection.prop('disabled', false);
                        }
                    }
                }
            });
        });
    });
</script>