<?php

// If settings set then loop products and target(s) to send like on single product page
$data = $this->getRequest()->getParams();
$sendURL = $block->getSendUrl();
?>

<?php if (!$block->isReady()) :?>
    <?php
    $configUrl = $this->getUrl(
        'adminhtml/system_config/edit/section/contentor_options'
    );

    echo sprintf(
        'Current configuration issues  : </br> %s',
        implode(',</br>', $block->getValidationMessages())
    );

    echo sprintf(
        '</br> Please configure your Contentor API <a href="%s">here</a> ',
        $configUrl
    );
    ?>

<?php else: ?>

<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            $(function() {
                doSend = function(formular) {
                    if(!document.getElementsByName("theend").value) {

                        const products = formular.products.value;

                        const source = formular.source.value;

                        const total = formular.total.value;

                        const deliverySpeed = formular.deliverySpeed.value;

                        const machineTranslation = formular.machineTranslation ? formular.machineTranslation.value : 'none';

                        let inputs = null;

                        if ( document.getElementById('configAttributesContentCreation') ) {
                             inputs = document.getElementById('configAttributesContentCreation').getElementsByTagName('input');
                        }

                        if ( document.getElementById('configAttributesContentCreationResponse') ) {
                            inputs = document.getElementById('configAttributesContentCreationResponse').getElementsByTagName('input');
                        }

                        let elesContentCreation = {};

                        if ( inputs ) {
                            for(var i = 0; i < inputs.length; i++) {

                                if(inputs[i].name.indexOf('attributesConfig') == 0) {

                                    let attributeName = '';

                                    let matches = inputs[i].name.match(/\[(.*?)\]/);

                                    if (matches) {
                                        attributeName = matches[1];
                                    }

                                    if ( attributeName !== '' ) {
                                        elesContentCreation[attributeName] = {
                                            word_count: $('#'+attributeName+'_word_count').val(),
                                            field_type: $('#'+attributeName+'_field_type').val(),
                                            context_value: $('#'+attributeName+'_context_value').val()
                                        };
                                    }
                                }
                            }
                        }

                        let targets;

                        if(formular.targets.type == 'select-multiple') {
                            targets = new Array;
                            for(x=0;x<formular.targets.length;x++) {
                                if(formular.targets[x].selected) {
                                    targets.push(formular.targets[x].value);
                                }
                            }
                            targets = targets.join(',');
                        } else {
                            targets = formular.targets.value;
                        }
                        $.post("<?php print $sendURL ?>", { products: products, source: source, targets: targets, total: total, deliverySpeed: deliverySpeed, machineTranslation: machineTranslation, attributesConfig: elesContentCreation }, function(data) {
                            document.getElementById('resultdiv').innerHTML = data;
                            doSend(document.getElementById('progressform'));
                        });
                    }
                }
            });
        });
</script>



<form id="productform">
<p>
    <?php
    if ($products = $this->getProductsWithFilter()) {
        $n = count($products);
        $prodList = implode(',', $products);
        print 'Submiting this form will send <b>' . $n . '</b> products';
        print '<input type="hidden" name="products" value="' . $prodList . '" id="prodlist">';
        print '<input type="hidden" name="total" value=0>';
    } else {
        print "Error, no data set";
    }
    ?>
</p>
<br><br>
<p>
    <h3>Source locale</h3>
    <?php
    // Get default locale from settings
    $defaultSource = $this->helper('Contentor\LocalizationApi\Helper\Data')->getConfig('contentor_options/source/sourcelocale');
    $localeList = $this->getLocaleList();
    ?>
    <select name="source">
        <option value="">Choose source language</option>
        <?php
        foreach ($localeList as $lang) {
            print '<option value="' . $lang['value'] . '"';
            if ($lang['value'] == $defaultSource) {
                print ' SELECTED';
            }
            print '>' . $lang['label'] . '</option>';
        }
        ?>
    </select>
    <br>
</p>
<br><br>
<p>
    <h3>Target store(s)</h3>
    <?php
    // Get default stores from settings
    $defaultstores = explode(',', $this->helper('Contentor\LocalizationApi\Helper\Data')->getConfig('contentor_options/targets/targetviews'));
    $storesStructure = $this->getStoreViews();

    print '<select name="targets" class="select multiselect" size="10" multiple="multiple">';

    foreach ($storesStructure as $website) {
        print '<optgroup label="' . $website['label'] . '"></optgroup>';
        foreach ($website['children'] as $store) {
            print '<optgroup label="    ' . $store['label'] . '"></optgroup>';
            foreach ($store['children'] as $storeview) {
                $id = $storeview['value'];
                $name = $storeview['label'];
                $locale = $this->getStoreLocale($id);
                //str_replace('_', '-', Mage::getStoreConfig('general/locale/code', $id));
                if (in_array($id, $defaultstores)) {
                    $checked = 'selected="selected"';
                } else {
                    $checked = '';
                }
                print '<option value="' . $id . '" ' . $checked . '>     ' . $name . ' (' . $locale .')</option>';
            }
        }
    }
    print '</select>';
    ?>
</p>
<?= $block->getChildHtml('contentor.delivery-speed'); ?><br>

<?php if( $block->getSyncType() !== \Contentor\LocalizationApi\Model\Product::CONTENT_CREATION_SYNC_TYPE ):?>
    <?= $block->getChildHtml('contentor.machine-translation'); ?><br>
<?php endif;?>

<?php if( $block->getSyncType() == \Contentor\LocalizationApi\Model\Product::CONTENT_CREATION_SYNC_TYPE ):?>
    <?= $block->getChildHtml('contentor.config-words-amount-block'); ?>
<br>
<?php endif;?>

</form>
<br><br>
<p>
    <button name="submitme" class="action-secondary" onClick="doSend(document.getElementById('productform'));"><span><?= $block->getLabelSubmitButton(); ?></span></button>
</p>
<br><br>
<p>
    <div id="resultdiv"></div>
</p>
<?php endif; ?>
