<?php

use Contentor\LocalizationApi\Block\Adminhtml\Administration\BulkProducts;
use Contentor\LocalizationApi\Block\Adminhtml\Administration\ContentCreationBulkProducts;
use Contentor\LocalizationApi\Model\Product;

/** @var BulkProducts|ContentCreationBulkProducts $block */
$data = $this->getRequest()->getParams();
$sendURL = $block->getSendUrl();
$dataViewModel = $block->getData('dataViewModel');
$defaultStores = $dataViewModel
    ? explode(',', $dataViewModel->getConfig('contentor_options/targets/targetviews'))
    : '';
$defaultSource = $dataViewModel ? $dataViewModel->getConfig('contentor_options/source/sourcelocale') : '';
?>

<?php if (!$block->isReady()) :?>
    <?php
    $configUrl = $this->getUrl(
        'adminhtml/system_config/edit/section/contentor_options'
    );

    echo sprintf(
        'Current configuration issues  : </br> %s',
        implode(',</br>', $block->getValidationMessages())
    );

    echo sprintf(
        '</br> Please configure your Contentor API <a href="%s">here</a> ',
        $configUrl
    );
    ?>

<?php else: ?>

<form id="productform">
<p>
    <?php
    if ($products = $this->getProductsWithFilter()) {
        $n = count($products);
        $prodList = implode(',', $products);
        print 'Submiting this form will send <b>' . $n . '</b> products';
        print '<input type="hidden" name="products" value="' . $prodList . '" id="prodlist">';
        print '<input type="hidden" name="total" value=0>';
    } else {
        print "Error, no data set";
    }
    ?>
</p>
<br><br>
<p>
    <h3>Source locale</h3>
    <?php $localeList = $this->getLocaleList(); ?>
    <select name="source">
        <option value="">Choose source language</option>
        <?php
        foreach ($localeList as $lang) {
            print '<option value="' . $lang['value'] . '"';
            if ($lang['value'] == $defaultSource) {
                print ' SELECTED';
            }
            print '>' . $lang['label'] . '</option>';
        }
        ?>
    </select>
    <br>
</p>
<br><br>
<p>
    <h3>Target store(s)</h3>
    <?php
    $storesStructure = $this->getStoreViews();

    print '<select name="targets" class="select multiselect" size="10" multiple="multiple">';

    foreach ($storesStructure as $website) {
        print '<optgroup label="' . $website['label'] . '"></optgroup>';
        foreach ($website['children'] as $store) {
            print '<optgroup label="    ' . $store['label'] . '"></optgroup>';
            foreach ($store['children'] as $storeview) {
                $id = $storeview['value'];
                $name = $storeview['label'];
                $locale = $this->getStoreLocale($id);
                if ($defaultStores && in_array($id, $defaultStores)) {
                    $checked = 'selected="selected"';
                } else {
                    $checked = '';
                }
                print '<option value="' . $id . '" ' . $checked . '>     ' . $name . ' (' . $locale .')</option>';
            }
        }
    }
    print '</select>';
    ?>
</p>
<?= $block->getChildHtml('contentor.delivery-speed'); ?><br>

<?= $block->getChildHtml('contentor.versioning'); ?><br>

<?php if ($block->getSyncType() !== Product::CONTENT_CREATION_SYNC_TYPE):?>
    <?= $block->getChildHtml('contentor.machine-translation'); ?><br>
<?php endif;?>

<?php if ($block->getSyncType() == Product::CONTENT_CREATION_SYNC_TYPE):?>
    <?= $block->getChildHtml('contentor.config-words-amount-block'); ?>
<br>
<?php endif;?>

</form>
<br><br>
<p data-mage-init='{"Contentor_LocalizationApi/js/sendRequest": {"sendUrl": "<?= $sendURL ?>"}}'>
    <button name="submitme" class="action-secondary"><span><?= $block->getLabelSubmitButton(); ?></span></button>
</p>
<br><br>
<p>
    <div id="resultdiv"></div>
</p>
<?php endif; ?>
